dir:
  results: 'results/'
  dataset: '../data_own/'

shape_dataset:
  id: sub-221CR_ses-20190515T160400 # my
  # id: sub-221CR_ses-20190514T142312
  # id: sub-231CR_ses-20190924T161413 # abhishek
  # id: sub-231CR_ses-20190921T144923
  # id: sub-KM131_ses-20180117T194023
  # id: sub-267CR_ses-20200331T161053
  # id: sub-245CR_ses-20200331T142427
  # id: sub-KF134_ses-20180208T171905

  win_len: 0.1

# mention x for stimulus, choice and rest
dim_x_z: [0, 1, 1]


rnn:  
  # rnn_type: 'GRU'
  bidirectional: True
  hidden_size: 16
  num_layers: 1
  dropout: 0.15
  softmax_temp: 1
  lr: 0.01
  weight_decay: 0.0001

  scheduler:
    which: ''
    cosine_restart_after: 120
    const_factor: 0.95

decoder:
  behavior_weight: 10

  stimulus_weight: 10
  choice_weight: 1
  
  which: 'cnn_indi'
  
  cnn:
    channels: [8, 8, 8]
    kernel_size: 3
    dropout: 0.2
    lr: 0.005
    weight_decay: 0

  rnn:
    layers: 1
    hidden_dim: 8
    lr: 0.001
    dropout: 0.3  

  linear:
    hidden_dims: [8, 8]
    dropout: 0.1
    lr: 0.0003

  scheduler:
    which: 'decay'
    cosine_restart_after: 120
    const_factor: 0.98

seed: 7

early_stop:
  patience: 25
  delta: 1
  test_every_new: 2

epochs: 2000
test_every: 20
plot_every: 5
batch_size: 32